language: go

go:
- tip # The latest version of Go.


before_install:
  - export GOROOT=$(go env GOROOT)


sudo: enabled
install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/_workspace/bin:$PATH"

script:
- "./build.sh"