language: go

go:
- tip # The latest version of Go.


before_install:
  - chmod +x build.sh

go_import_path: src/github.com/Niraj-Fonseka/webapp_go

sudo: enabled

script:
- go env
- echo $GOPATH
- ls $GOPATH/src
- "./build.sh"