language: go

go:
- tip # The latest version of Go.


before_install:
  - export GOROOT=$(go env GOROOT)
  - chmod +x build.sh


sudo: enabled
install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}//bin:$PATH"

script:
- go env
- "./build.sh"